(function() {var implementors = {};
implementors['rustc-serialize'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rustc-serialize/json/enum.Json.html' title='rustc-serialize::json::Json'>Json</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rustc-serialize/json/enum.ErrorCode.html' title='rustc-serialize::json::ErrorCode'>ErrorCode</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rustc-serialize/json/enum.ParserError.html' title='rustc-serialize::json::ParserError'>ParserError</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rustc-serialize/json/enum.DecoderError.html' title='rustc-serialize::json::DecoderError'>DecoderError</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rustc-serialize/json/enum.JsonEvent.html' title='rustc-serialize::json::JsonEvent'>JsonEvent</a>","<a class='stability Stable' title='Stable'></a>impl&lt;'l&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rustc-serialize/json/enum.StackElement.html' title='rustc-serialize::json::StackElement'>StackElement</a>&lt;'l&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
